services:
  - type: web
    name: kaziranga-site
    env: static
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /contact
        destination: /contact.html
      - type: rewrite
        source: /notice
        destination: /notice.html
      - type: rewrite
        source: /projects
        destination: /projects.html
      - type: rewrite
        source: /purpose
        destination: /purpose.html
      - type: rewrite
        source: /privacy
        destination: /privacy.html
      - type: rewrite
        source: /terms
        destination: /terms.html
